### ISSUE TITLE
在服务器中禁用 google-chrome 自动更新

### ISSUE THREAD

**Issue by MetaT1an** [siliconx/py#1]
使用`apt update`升级软件包时会自动更新 chrome ，驱动如果安装的比较早，后续使用可能会出现 chrome 与驱动版本相差太多，导致脚本使用出现潜在问题。

服务器上的 chrome 不常用，可以使用`apt-mark`命令禁止其自动更新，保持与安装时驱动的版本一致。

```shell
sudo apt-mark hold google-chrome-stable  # prevent chrome from being automatically upgraded
sudo apt-mark showhold  # show packages on hold
```

😝参阅：[http://manpages.ubuntu.com/manpages/bionic/man8/apt-mark.8.html](http://manpages.ubuntu.com/manpages/bionic/man8/apt-mark.8.html)

**Comment by siliconx** [comment]
赞👍
